name: add-label

on:
  issues:
    types: [opened]

jobs:
  apply-label:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}

      - name: Add Label
        run: |
          github.issues.addLabels({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: ['Triage']
          })

      - name: Get issue
        run: |
          github.issues.get({
            owner: context.repo.owner,
            repo:  context.repo.repo,
            issue_number: context.issue.number,
          });
