name: add-label

on:
  issues:
    types: [opened]

jobs:
  apply-label:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['Triage']
            })
            github.issues.get({
              owner: context.repo.owner,
              repo:  context.repo.repo,
              issue_number: context.issue.number,
            });
          result-encoding: string
      - name: Get result
        run: echo "${{steps.set-result.outputs.result}}"
