name: run-make-link

on:
  issues:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Create local changes
        # TODO: GET ISSUE TITLE
        run: |
          make link

      - name: Commit files
        run: |
          git config --local user.email "dm.havimaki@gmail.com"
          git config --local user.name "user.name=Havimaki"
          git commit -m "Add changes"
          git add -A

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
