name: add-to-backlog

on:
  issues:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Add to backlog
        run: make link
